final Map<String, List<Object>> disablity = {
"Acid Attack Victim":["",],
"Autism Spectrum Disorder":["",],
"Blindness":["",],
"Cerebral Palsy":["",],
"Chronic Neurological Conditions":["",],
"Hearing Impairment":["",],
"Hemophilia":["",],
"Intellectual Disability":["",],
"Leprosy cured":["",],
"Locomotor Disability":["",],
"Low Vision":["",],
"Mental Illness":["",],
"Multiple Disability":["",],
"Multiple Sclerosis":["",],
"Muscular Dystrophy":["",],
"Parkinson's Disease":["",],
"Short Stature/Dwarfism":["",],
"Sickle Cell Disease":["",],
"Specific Learning Disabilities":["",],
"Speech and Language Disability":["",],
"Thalassemia":["",],
};
